# ==============================
# APP
# ==============================
spring.application.name=Emprenet

# IMPORTANTE PARA RAILWAY
server.port=${PORT:8080}

# ==============================
# DATABASE (NEON POSTGRESQL)
# ==============================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# ==============================
# JPA / HIBERNATE
# ==============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==============================
# THYMELEAF
# ==============================
spring.thymeleaf.cache=false

# ==============================
# DEVTOOLS (opcional)
# ==============================
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# ==============================
# MAIL (GMAIL SMTP)
# ==============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=palominoquispepercyelvis@gmail.com
spring.mail.password=ajymdshnxwzkfigd

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true